apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "yamtrack.fullname" . }}-yamtrack'
data:
  REDIS_URL: redis://{{ include "yamtrack.fullname" . }}-redis:6379
  SECRET: {{ .Values.yamtrack.secret | quote }}
  TZ: Europe/Berlin
