apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "yamtrack.fullname" . }}-redis'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "yamtrack.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: redis
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "yamtrack.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - image: '{{ tpl .Values.redis.repository.image $ }}:{{ tpl .Values.redis.repository.tag $ }}'
          imagePullPolicy: {{ .Values.redis.pullPolicy }}
          name: yamtrack-redis
          ports:
            - containerPort: 6379
              name: redis
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          livenessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1500m
              memory: 2400Mi
            requests:
              cpu: 75m
              memory: 200Mi
          {{- if .Values.redis.nodeSelector }}
          nodeSelector:
            {{- .Values.redis.nodeSelector | toYaml | nindent 8 }}
          {{- end }}
