apiVersion: v1
kind: Service
metadata:
  name: '{{ include "yamtrack.fullname" . }}-redis'
  labels:
    {{- include "yamtrack.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
  selector:
    {{- include "yamtrack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
